windows:
  language:
    PO:
      device_name: Dispositivo
      power_name: Alimentação
      audio_name: Áudio
      display_name: Ecrã e Câmara
      input_name: Introdução e Acessórios
      advanced_name: Advanced Settings
    US:
      device_name: Device
      power_name: Power
      audio_name: Audio
      display_name: Display & Camera
      input_name: Input & Accessories
      advanced_name: Advanced Settings
    AR:
      device_name: الجهاز
      power_name: الطاقة
      audio_name: صوت
      display_name: جهاز العرض والكاميرا
      input_name: الإدخال والملحقات
      #advanced_name: Advanced Settings
    BR:
      device_name: Dispositivo
      power_name: Energia
      audio_name: Áudio
      display_name: Monitor e câmera
      input_name: Entrada e acessórios
      advanced_name: Advanced Settings
    CR:
      device_name: Uređaj
      power_name: Napajanje
      audio_name: Zvuk
      display_name: Prikaz i kamera
      input_name: Unos i pomagala
      advanced_name: Advanced Settings
    CZ:
      device_name: Zařízení
      power_name: Napájení
      audio_name: Zvuk
      display_name: Displej a kamera
      input_name: Vstup & Příslušenství
      advanced_name: Advanced Settings
    DK:
      device_name: Enhed
      power_name: Strøm
      audio_name: Lyd
      display_name: Skærm og kamera
      input_name: Input og tilbehør
      advanced_name: Advanced Settings
    FI:
      device_name: Laite
      power_name: Virta
      audio_name: Äänitoiminnot
      display_name: Näyttö ja kamera
      input_name: Syöttö ja lisävarusteet
      advanced_name: Advanced Settings
    FR:
      device_name: Périphérique
      power_name: Alimentation
      audio_name: Audio
      display_name: Écran et caméra
      input_name: Saisie et accessoires
      advanced_name: Advanced Settings
    GK:
      device_name: Συσκευή
      power_name: Ενέργεια
      audio_name: Ήχος
      display_name: Οθόνη & Κάμερα
      input_name: Εισαγωγή και αξεσουάρ
      advanced_name: Advanced Settings
    GR:
      device_name: Gerät
      power_name: Stromversorgung
      audio_name: Audio
      display_name: Anzeige und Kamera
      input_name: Eingabe und Zubehör
      advanced_name: Advanced Settings
    HE:
      device_name: התקן
      power_name: צריכת חשמל
      audio_name: שמע
      display_name: תצוגה ומצלמה
      input_name: קלט ועזרים
      advanced_name: Advanced Settings
    HU:
      device_name: Eszköz
      power_name: Tápellátás
      audio_name: Hang
      display_name: Képernyő és kamera
      input_name: Bevitel és kellékek
      advanced_name: Advanced Settings
    IT:
      device_name: Dispositivo
      power_name: Alimentazione
      audio_name: Audio
      display_name: Schermo e fotocamera
      input_name: Input e accessori
      advanced_name: Advanced Settings
    JP:
      device_name: qs-lnk-my-device-settings
      power_name: 電源
      audio_name: オーディオ
      display_name: ディスプレイとカメラ
      input_name: 入力およびアクセサリ
      advanced_name: Advanced Settings
    KR:
      device_name: 장치
      power_name: 전원
      audio_name: 오디오
      display_name: 디스플레이 및 카메라
      input_name: 입력 및 액세서리
      advanced_name: Advanced Settings
    NL:
      device_name: Apparaat
      power_name: Energiebeheer
      audio_name: Audio
      display_name: Weergave en camera
      input_name: Invoer & bureau-accessoires
      advanced_name: Advanced Settings
    Norwegian:
      device_name: Enhet
      power_name: Strøm
      audio_name: Lyd
      display_name: Skjerm og kamera
      input_name: Inndata og tilbehør
      advanced_name: Advanced Settings
    PL:
      device_name: Urządzenie
      power_name: Zasilanie
      audio_name: Dźwięk
      display_name: Ekran i kamera
      input_name: Wprowadzanie i akcesoria
      advanced_name: Advanced Settings
    RO:
      device_name: Dispozitiv
      power_name: Alimentare
      audio_name: Audio
      display_name: Afișaj și cameră
      input_name: Intrare și accesorii
      advanced_name: Advanced Settings
    RU:
      device_name: Устройство
      power_name: Питание
      audio_name: Звук
      display_name: Дисплей и камера
      input_name: Ввод и аксессуары
      advanced_name: Advanced Settings
    SC:
      device_name: 我的设备
      power_name: 电源管理
      audio_name: 音频
      display_name: 显示屏和摄像头
      input_name: 输入和附件
      #advanced_name: Advanced Settings
    SH:
      device_name: Uređaj
      power_name: Napajanje
      audio_name: Audio
      display_name: Ekran i kamera
      input_name: Unos i pribor
      advanced_name: Advanced Settings
    SK:
      device_name: Zariadenie
      power_name: Napájanie
      audio_name: Zvuk
      display_name: Obrazovka a kamera
      input_name: Vstup a príslušenstvo
      advanced_name: Advanced Settings
    SL:
      device_name: Naprava
      power_name: Napajanje
      audio_name: Zvok
      display_name: Zaslon in kamera
      input_name: Vnašanje in pripomočki
      advanced_name: Advanced Settings
    SP:
      device_name: Dispositivo
      power_name: Energía
      audio_name: Audio
      display_name: Pantalla y cámara
      input_name: Entrada y accesorios
      advanced_name: Advanced Settings
    SV:
      device_name: Enhet
      power_name: Ström
      audio_name: Ljud
      display_name: Bildskärm och kamera
      input_name: Inmatning och tillbehör
      advanced_name: Advanced Settings
    TC:
      device_name: 裝置
      power_name: 電源
      audio_name: 音效
      display_name: 顯示器和攝影機
      input_name: 輸入和配件
      advanced_name: Advanced Settings
    TU:
      device_name: Cihaz
      power_name: Güç
      audio_name: Ses
      display_name: Ekran ve Kamera
      input_name: Giriş ve Aksesuarlar
      advanced_name: Advanced Settings
    UA:
      device_name: Пристрій
      power_name: Живлення
      audio_name: Звук
      display_name: Дисплей і камера
      input_name: Введення й аксесуари
      advanced_name: Advanced Settings
  power_page:
    device: menu-main-nav-lnk-dropdown-toggle-device
    device_name: Device
    all_settings: qs-lnk-my-device-settings
    power: menu-main-nav-lnk-dropdown-menu-device-device-settings-1
    power_name: Power
    toolbar_description_name: Pin Lenovo Vantage Toolbar to Windows taskbar to easily access the most popular settings, view warranty options, submit feedback, and launch Lenovo Vantage to get customized offerings and updates.
  audio_page:
    audio: menu-main-nav-lnk-dropdown-menu-device-device-settings-2
    audio_name: Audio
  display_page:
    display: menu-main-nav-lnk-dropdown-menu-device-device-settings-3
    display_name: Display & Camera
  input_page:
    input: menu-main-nav-lnk-dropdown-menu-device-device-settings-4
    input_name: Input & Accessories
  advanced_settings_page:
    advanced: menu-main-nav-lnk-dropdown-menu-device-device-settings-5
    advanced_name: Advanced Settings

Language:
  a: 6
  b: 7
  AR: Arabic
  BR: Brazilian Portuguese