desired_capabilities:
  platformName: Android
  deviceName: Redmi_Note_8_Pro
  platformVersion: "11"
  appPackage: com.tencent.mobileqq
  appActivity: com.tencent.mobileqq.activity.SplashActivity
  automationName: UiAutomator2
  noReset: "true"